name: SuperbVote
main: io.minimum.minecraft.superbvote.SuperbVote
author: tuxed
version: ${project.version}
depend: [Votifier]
softdepend: [Vault, PlaceholderAPI]
api-version: "1.20"
folia-supported: true

commands:
  superbvote:
    description: SuperbVote main command.
    aliases: [sv]
  vote:
    description: SuperbVote vote command.
  votestreak:
    description: SuperbVote vote streak command.
    aliases: [vstreak]
  voteparty:
    description: SuperbVote voteparty command.
    aliases: [vp]

permissions:
  superbvote.notify:
    default: true
  superbvote.votes.others:
    default: op
  superbvote.admin:
    default: op
  superbvote.voteparty.*:
    default: op
    children:
      superbvote.voteparty.setcounter: true
      superbvote.voteparty.addvotes: true
      superbvote.voteparty.startparty: true
